In [2]:
df = pd.read_csv("student_scores.csv")
df.head()

   StudyHours  Score
0         4.4   43.3
1         9.6   87.3
2         7.6   67.8
3         6.4   56.1
4         2.4   14.2

In [4]:
# First 5 rows
df.head()

   StudyHours  Score
0         4.4   43.3
1         9.6   87.3
2         7.6   67.8
3         6.4   56.1
4         2.4   14.2

In [5]:
# Last 5 rows
df.tail()

    StudyHours  Score
46         3.8   38.8
47         5.7   52.9
48         5.9   50.5
49         2.7   26.9
50         6.4   56.1

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudyHours  50 non-null     float64
 1   Score       50 non-null     float64
dtypes: float64(2)
memory usage: 948.0 bytes

In [7]:
# Summary statistics for numeric columns
df.describe()

       StudyHours      Score
count   50.000000  50.000000
mean     4.974000  45.900000
std      2.563624  23.280578
min      1.200000   9.400000
25%      2.700000  27.325000
50%      4.950000  47.800000
75%      6.500000  60.050000
max      9.700000  93.300000

In [8]:
# Check for missing values
df.isnull().sum()

StudyHours    1
Score         1
dtype: int64

In [9]:
# Check for duplicate rows
df.duplicated().sum()

np.int64(1)